// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/control/control.proto

package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusRequest) Reset()         { *m = StatusRequest{} }
func (m *StatusRequest) String() string { return proto.CompactTextString(m) }
func (*StatusRequest) ProtoMessage()    {}
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_dee4c66a1ec05a00, []int{0}
}
func (m *StatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusRequest.Unmarshal(m, b)
}
func (m *StatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusRequest.Marshal(b, m, deterministic)
}
func (dst *StatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusRequest.Merge(dst, src)
}
func (m *StatusRequest) XXX_Size() int {
	return xxx_messageInfo_StatusRequest.Size(m)
}
func (m *StatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StatusRequest proto.InternalMessageInfo

type StatusResponse struct {
	Name                 string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Increment            uint64                 `protobuf:"varint,2,opt,name=Increment,proto3" json:"Increment,omitempty"`
	Timeout              string                 `protobuf:"bytes,3,opt,name=Timeout,proto3" json:"Timeout,omitempty"`
	Promised             uint64                 `protobuf:"varint,4,opt,name=Promised,proto3" json:"Promised,omitempty"`
	ID                   uint64                 `protobuf:"varint,5,opt,name=ID,proto3" json:"ID,omitempty"`
	Holder               string                 `protobuf:"bytes,6,opt,name=Holder,proto3" json:"Holder,omitempty"`
	Peers                []*StatusResponse_Peer `protobuf:"bytes,7,rep,name=Peers,proto3" json:"Peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StatusResponse) Reset()         { *m = StatusResponse{} }
func (m *StatusResponse) String() string { return proto.CompactTextString(m) }
func (*StatusResponse) ProtoMessage()    {}
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_dee4c66a1ec05a00, []int{1}
}
func (m *StatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse.Unmarshal(m, b)
}
func (m *StatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse.Marshal(b, m, deterministic)
}
func (dst *StatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse.Merge(dst, src)
}
func (m *StatusResponse) XXX_Size() int {
	return xxx_messageInfo_StatusResponse.Size(m)
}
func (m *StatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse proto.InternalMessageInfo

func (m *StatusResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StatusResponse) GetIncrement() uint64 {
	if m != nil {
		return m.Increment
	}
	return 0
}

func (m *StatusResponse) GetTimeout() string {
	if m != nil {
		return m.Timeout
	}
	return ""
}

func (m *StatusResponse) GetPromised() uint64 {
	if m != nil {
		return m.Promised
	}
	return 0
}

func (m *StatusResponse) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *StatusResponse) GetHolder() string {
	if m != nil {
		return m.Holder
	}
	return ""
}

func (m *StatusResponse) GetPeers() []*StatusResponse_Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type StatusResponse_Peer struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusResponse_Peer) Reset()         { *m = StatusResponse_Peer{} }
func (m *StatusResponse_Peer) String() string { return proto.CompactTextString(m) }
func (*StatusResponse_Peer) ProtoMessage()    {}
func (*StatusResponse_Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_control_dee4c66a1ec05a00, []int{1, 0}
}
func (m *StatusResponse_Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusResponse_Peer.Unmarshal(m, b)
}
func (m *StatusResponse_Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusResponse_Peer.Marshal(b, m, deterministic)
}
func (dst *StatusResponse_Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusResponse_Peer.Merge(dst, src)
}
func (m *StatusResponse_Peer) XXX_Size() int {
	return xxx_messageInfo_StatusResponse_Peer.Size(m)
}
func (m *StatusResponse_Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusResponse_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_StatusResponse_Peer proto.InternalMessageInfo

func (m *StatusResponse_Peer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusRequest)(nil), "StatusRequest")
	proto.RegisterType((*StatusResponse)(nil), "StatusResponse")
	proto.RegisterType((*StatusResponse_Peer)(nil), "StatusResponse.Peer")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControlClient is the client API for Control service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControlClient interface {
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
}

type controlClient struct {
	cc *grpc.ClientConn
}

func NewControlClient(cc *grpc.ClientConn) ControlClient {
	return &controlClient{cc}
}

func (c *controlClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/Control/Status", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControlServer is the server API for Control service.
type ControlServer interface {
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
}

func RegisterControlServer(s *grpc.Server, srv ControlServer) {
	s.RegisterService(&_Control_serviceDesc, srv)
}

func _Control_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Control/Status",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Control_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Control",
	HandlerType: (*ControlServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Status",
			Handler:    _Control_Status_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/control/control.proto",
}

func init() {
	proto.RegisterFile("proto/control/control.proto", fileDescriptor_control_dee4c66a1ec05a00)
}

var fileDescriptor_control_dee4c66a1ec05a00 = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4e, 0xc3, 0x30,
	0x10, 0x45, 0x95, 0x34, 0x4d, 0xe8, 0x20, 0x52, 0x69, 0x84, 0xd0, 0x28, 0xb0, 0x88, 0xba, 0x0a,
	0x2c, 0x8c, 0x54, 0xb8, 0x01, 0x5d, 0x90, 0x0d, 0xaa, 0x0c, 0x17, 0x28, 0xed, 0x2c, 0x2a, 0xd5,
	0x9e, 0x62, 0x3b, 0x77, 0xe6, 0x18, 0xa8, 0x0e, 0x01, 0x05, 0xb1, 0xf2, 0xfc, 0x67, 0xff, 0x2f,
	0xcf, 0x87, 0xeb, 0xa3, 0x93, 0x20, 0xf7, 0x5b, 0xb1, 0xc1, 0xc9, 0x61, 0x38, 0x55, 0xa4, 0x8b,
	0x39, 0x5c, 0xbc, 0x86, 0x4d, 0xe8, 0xbc, 0xe6, 0x8f, 0x8e, 0x7d, 0x58, 0x7c, 0x26, 0x50, 0x0e,
	0xc4, 0x1f, 0xc5, 0x7a, 0x46, 0x84, 0xec, 0x65, 0x63, 0x98, 0x92, 0x3a, 0x69, 0x66, 0x3a, 0xce,
	0x78, 0x03, 0xb3, 0xd6, 0x6e, 0x1d, 0x1b, 0xb6, 0x81, 0xd2, 0x3a, 0x69, 0x32, 0xfd, 0x0b, 0x90,
	0xa0, 0x78, 0xdb, 0x1b, 0x96, 0x2e, 0xd0, 0x24, 0x9a, 0x06, 0x89, 0x15, 0x9c, 0xad, 0x9d, 0x98,
	0xbd, 0xe7, 0x1d, 0x65, 0xd1, 0xf6, 0xa3, 0xb1, 0x84, 0xb4, 0x5d, 0xd1, 0x34, 0xd2, 0xb4, 0x5d,
	0xe1, 0x15, 0xe4, 0xcf, 0x72, 0xd8, 0xb1, 0xa3, 0x3c, 0x86, 0x7c, 0x2b, 0xbc, 0x83, 0xe9, 0x9a,
	0xd9, 0x79, 0x2a, 0xea, 0x49, 0x73, 0xbe, 0xbc, 0x54, 0xe3, 0xff, 0xaa, 0xd3, 0xa5, 0xee, 0x9f,
	0x54, 0x15, 0x64, 0xa7, 0xe1, 0xbf, 0x1d, 0x96, 0x8f, 0x50, 0x3c, 0xf5, 0x65, 0xe0, 0x2d, 0xe4,
	0x7d, 0x08, 0x96, 0x6a, 0xd4, 0x47, 0x35, 0xff, 0x93, 0xfe, 0x9e, 0xc7, 0xe2, 0x1e, 0xbe, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x37, 0xde, 0x0e, 0x5a, 0x57, 0x01, 0x00, 0x00,
}
