---
name: kanta
increment: 4
timeout: 500ms
listen: 0.0.0.0:9004
peers:
- name: satsuki
  address: 127.0.0.1:9001
- name: mei
  address: 127.0.0.1:9002
- name: totoro
  address: 127.0.0.1:9003
- name: catbus
  address: 127.0.0.1:9005
