---
name: totoro
increment: 3
timeout: 500ms
listen: 0.0.0.0:9003
peers:
- name: satsuki
  address: 127.0.0.1:9001
- name: mei
  address: 127.0.0.1:9002
- name: kanta
  address: 127.0.0.1:9004
- name: catbus
  address: 127.0.0.1:9005
