---
- name: install gcc
  apt:
    name: gcc
    update_cache: yes

- name: install go and protoc
  shell: snap install --classic {{ item }}
  loop:
    - go
    - protobuf

- name: install mage
  shell: go get -u github.com/magefile/mage

- name: clone skinny repository
  git:
    repo: https://github.com/danrl/skinny.git
    dest: /skinny
    force: yes
  notify: restart skinny service

- name: build skinny 
  shell: /root/go/bin/mage builddeps && /root/go/bin/mage
  args:
    chdir: /skinny
  notify: restart skinny service

- name: create skinny configuration directory
  file:
    path: /etc/skinny
    state: directory
    mode: 0755

- name: copy skinny configuration file
  copy:
    src: "{{ instance_name }}.yml"
    dest: /etc/skinny/config.yml
  notify: restart skinny service

- name: copy skinny unit file
  copy:
    src: skinny.service
    dest: /etc/systemd/system/skinny.service
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  notify: restart skinny service
