name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: go mod vendor

    - name: Vet
      run: go vet -v $(go list ./... | grep -v /vendor/)

    - name: Build
      run: go build -v $(go list ./... | grep -v /vendor/)

    - name: Test
      run: go test -v -race $(go list ./... | grep -v /vendor/)

    - name: Coverage
      run: |
          echo "" > coverage.txt
          for FNAME in $(go list ./... | grep -v vendor); do
            go test -race -coverprofile=profile.out -covermode=atomic ${FNAME}
            if [ -f profile.out ]; then
              cat profile.out >> coverage.txt
              rm profile.out
            fi
          done
          bash <(curl -s https://codecov.io/bash)
